### ISSUE TITLE
cheetah v1 - roadmap

### ISSUE THREAD

**Issue by boywithkeyboard** [azurystudio/cheetah#3]
These are some of the changes and features that need to be addressed before a v1 release.

Feedback is welcome!

### Tasks:

- [ ] Option to transform FormData request body to JSON
- [ ] Make `waitUntil` function suitable for Deno Deploy and self-hosting
- [ ] Implement a fallback for `c.req.geo` on Deno
